// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Context;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316164657_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Tables.DbSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        });
                });

            modelBuilder.Entity("Models.Tables.Giornata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aperta")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Giornate");
                });

            modelBuilder.Entity("Models.Tables.Listino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SettoreId")
                        .HasColumnType("int");

                    b.Property<int>("TariffaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SettoreId");

                    b.HasIndex("TariffaId");

                    b.ToTable("Listini");
                });

            modelBuilder.Entity("Models.Tables.Operatore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abilitato")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Pass")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Operatori");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Abilitato = true,
                            Nome = "ADMIN",
                            Pass = 0,
                            Password = "ADMIN",
                            PersonId = -2
                        });
                });

            modelBuilder.Entity("Models.Tables.Permesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OperatoreId")
                        .HasColumnType("int");

                    b.Property<int>("PostazioneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperatoreId");

                    b.HasIndex("PostazioneId");

                    b.ToTable("Permessi");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            OperatoreId = -1,
                            PostazioneId = -1
                        });
                });

            modelBuilder.Entity("Models.Tables.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Natoil")
                        .HasColumnType("int");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniqueParam")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("Id");

                    b.HasIndex("UniqueParam")
                        .IsUnique();

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            FirstName = "SOCIO",
                            Natoil = 21000101,
                            SurName = "VIRTUALE",
                            UniqueParam = "VIRSOC21000101"
                        },
                        new
                        {
                            Id = -999,
                            FirstName = "Di Servizio",
                            Natoil = 21000101,
                            SurName = "Tessera",
                            UniqueParam = "TESSER21000101"
                        },
                        new
                        {
                            Id = -2,
                            FirstName = "SOCIO",
                            Natoil = 21000101,
                            SurName = "AMMINISTRATORE",
                            UniqueParam = "AMMSOC21000101"
                        },
                        new
                        {
                            Id = -3,
                            FirstName = "Non Importato",
                            Natoil = 21000101,
                            SurName = "Socio",
                            UniqueParam = "SCOSOC21000101"
                        });
                });

            modelBuilder.Entity("Models.Tables.Postazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("TipoPostazioneId")
                        .HasColumnType("int");

                    b.Property<int>("TipoRientroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoPostazioneId");

                    b.HasIndex("TipoRientroId");

                    b.ToTable("Postazioni");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Nome = "Amministratore base",
                            TipoPostazioneId = 1,
                            TipoRientroId = -1
                        });
                });

            modelBuilder.Entity("Models.Tables.Reparto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostazioneId")
                        .HasColumnType("int");

                    b.Property<int>("SettoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostazioneId");

                    b.HasIndex("SettoreId");

                    b.ToTable("Reparti");
                });

            modelBuilder.Entity("Models.Tables.Settore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("TipoSettoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoSettoreId");

                    b.ToTable("Settori");
                });

            modelBuilder.Entity("Models.Tables.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abilitato")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroSocio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSocio")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("Soci");
                });

            modelBuilder.Entity("Models.Tables.Tariffa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFreeDrink")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Tariffe");
                });

            modelBuilder.Entity("Models.Tables.Tessera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abilitato")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroTessera")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Scadenza")
                        .HasColumnType("int");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroTessera")
                        .IsUnique();

                    b.HasIndex("SocioId");

                    b.ToTable("Tessere");
                });

            modelBuilder.Entity("Models.Tables.TipoPostazione", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("TipiPostazione");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Amministratore"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Cassa"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Bar"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Guardaroba"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Pulizie"
                        });
                });

            modelBuilder.Entity("Models.Tables.TipoRientro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurataOre")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("TipiRientro");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DurataOre = 0,
                            Nome = "Nessuno"
                        },
                        new
                        {
                            Id = -2,
                            DurataOre = 0,
                            Nome = "Giornata"
                        });
                });

            modelBuilder.Entity("Models.Tables.TipoSettore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("TipiSettore");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Nome = "Ingressi"
                        },
                        new
                        {
                            Id = -2,
                            Nome = "Standard"
                        });
                });

            modelBuilder.Entity("Models.Tables.Listino", b =>
                {
                    b.HasOne("Models.Tables.Settore", "Settore")
                        .WithMany("Listini")
                        .HasForeignKey("SettoreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Tables.Tariffa", "Tariffa")
                        .WithMany("Listini")
                        .HasForeignKey("TariffaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Settore");

                    b.Navigation("Tariffa");
                });

            modelBuilder.Entity("Models.Tables.Operatore", b =>
                {
                    b.HasOne("Models.Tables.Person", "Person")
                        .WithOne("Operatore")
                        .HasForeignKey("Models.Tables.Operatore", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Models.Tables.Permesso", b =>
                {
                    b.HasOne("Models.Tables.Operatore", "Operatore")
                        .WithMany("Permessi")
                        .HasForeignKey("OperatoreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Tables.Postazione", "Postazione")
                        .WithMany("Permessi")
                        .HasForeignKey("PostazioneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Operatore");

                    b.Navigation("Postazione");
                });

            modelBuilder.Entity("Models.Tables.Postazione", b =>
                {
                    b.HasOne("Models.Tables.TipoPostazione", "TipoPostazione")
                        .WithMany("Postazioni")
                        .HasForeignKey("TipoPostazioneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Tables.TipoRientro", "TipoRientro")
                        .WithMany("Postazioni")
                        .HasForeignKey("TipoRientroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TipoPostazione");

                    b.Navigation("TipoRientro");
                });

            modelBuilder.Entity("Models.Tables.Reparto", b =>
                {
                    b.HasOne("Models.Tables.Postazione", "Postazione")
                        .WithMany("Reparti")
                        .HasForeignKey("PostazioneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Tables.Settore", "Settore")
                        .WithMany("Reparti")
                        .HasForeignKey("SettoreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Postazione");

                    b.Navigation("Settore");
                });

            modelBuilder.Entity("Models.Tables.Settore", b =>
                {
                    b.HasOne("Models.Tables.TipoSettore", "TipoSettore")
                        .WithMany("Settori")
                        .HasForeignKey("TipoSettoreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TipoSettore");
                });

            modelBuilder.Entity("Models.Tables.Socio", b =>
                {
                    b.HasOne("Models.Tables.Person", "Person")
                        .WithMany("Soci")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Models.Tables.Tessera", b =>
                {
                    b.HasOne("Models.Tables.Socio", "Socio")
                        .WithMany("Tessere")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Models.Tables.Operatore", b =>
                {
                    b.Navigation("Permessi");
                });

            modelBuilder.Entity("Models.Tables.Person", b =>
                {
                    b.Navigation("Operatore");

                    b.Navigation("Soci");
                });

            modelBuilder.Entity("Models.Tables.Postazione", b =>
                {
                    b.Navigation("Permessi");

                    b.Navigation("Reparti");
                });

            modelBuilder.Entity("Models.Tables.Settore", b =>
                {
                    b.Navigation("Listini");

                    b.Navigation("Reparti");
                });

            modelBuilder.Entity("Models.Tables.Socio", b =>
                {
                    b.Navigation("Tessere");
                });

            modelBuilder.Entity("Models.Tables.Tariffa", b =>
                {
                    b.Navigation("Listini");
                });

            modelBuilder.Entity("Models.Tables.TipoPostazione", b =>
                {
                    b.Navigation("Postazioni");
                });

            modelBuilder.Entity("Models.Tables.TipoRientro", b =>
                {
                    b.Navigation("Postazioni");
                });

            modelBuilder.Entity("Models.Tables.TipoSettore", b =>
                {
                    b.Navigation("Settori");
                });
#pragma warning restore 612, 618
        }
    }
}
